# Generated by Django 5.0.3 on 2024-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('owner_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_salaries', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_misc_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mechanic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_staff_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
