# Generated by Django 5.0.3 on 2024-09-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0002_remove_truck_region_rubbertransport_number_of_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('driver_road_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_and_misc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oil_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camions.truck')),
            ],
        ),
    ]
