# Generated by Django 5.0.3 on 2024-09-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camions', '0002_remove_truck_region_rubbertransport_number_of_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_margin', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_deductions', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camions.truck')),
            ],
        ),
    ]
