# Generated by Django 5.0.3 on 2024-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='region',
        ),
        migrations.AddField(
            model_name='rubbertransport',
            name='number_of_truck',
            field=models.IntegerField(default=1),
        ),
    ]
