# Generated by Django 5.0.3 on 2024-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0002_remove_truck_region_rubbertransport_number_of_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubbertransport',
            name='tons_of_rubber',
            field=models.FloatField(default=0.0),
        ),
    ]
