# Generated by Django 5.0.3 on 2024-12-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0003_alter_rubbertransport_tons_of_rubber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubbertransport',
            name='number_of_truck',
        ),
        migrations.AddField(
            model_name='rubbertransport',
            name='number_of_trucks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rubbertransport',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubber_transports', to='camions.truck'),
        ),
    ]
