# Generated by Django 5.0.3 on 2024-12-15 04:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0004_remove_rubbertransport_number_of_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubbertransport',
            name='tons_of_rubber',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
