# Generated by Django 5.0.3 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0006_remove_rubbertransport_number_of_trucks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubbertransport',
            name='recette',
        ),
        migrations.AddField(
            model_name='rubbertransport',
            name='number_of_trucks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
