# Generated by Django 5.0.3 on 2024-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0007_remove_rubbertransport_recette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='matriculation_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(fields=('matriculation_number', 'created_at'), name='unique_daily_matriculation'),
        ),
    ]
